name: "Tests PHP 7.4"

on: [push, pull_request, workflow_dispatch]

jobs:
  unit-tests-7-4:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - uses: php-actions/composer@v6

    - uses: php-actions/phpunit@v4
      with:
        php_version: '7.4'
        configuration: 'phpunit.xml'
        testsuite: 'unit'